// ------------------------------------------------------------------------------------------------
// <copyright file="HtmlReportGenerator.cs" company="Starion Group S.A.">
//
//   Copyright 2017-2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace ECoreNetto.Reporting.Generators
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;

    using ECoreNetto.Extensions;
    using ECoreNetto.Reporting.Drawing;

    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.Abstractions;

    /// <summary>
    /// The purpose of the <see cref="HtmlReportGenerator"/> is to generate an HTML report of an
    /// Ecore Model
    /// </summary>
    public class HtmlReportGenerator : HandleBarsReportGenerator, IHtmlReportGenerator
    {
        /// <summary>
        /// The <see cref="ILogger"/> used to log
        /// </summary>
        private readonly ILogger<HtmlReportGenerator> logger;

        /// <summary>
        /// The <see cref="IInheritanceDiagramRenderer"/> used to render the inheritance diagrams
        /// </summary>
        private readonly IInheritanceDiagramRenderer inheritanceDiagramRenderer;

        /// <summary>
        /// The <see cref="IAssociationDiagramRenderer"/> used to render the per-class association diagrams
        /// </summary>
        private readonly IAssociationDiagramRenderer associationDiagramRenderer;

        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlReportGenerator"/> class.
        /// </summary>
        /// <param name="loggerFactory">
        /// The (injected) <see cref="ILoggerFactory"/> used to set up logging
        /// </param>
        public HtmlReportGenerator(ILoggerFactory? loggerFactory = null)
            : this(null, null, loggerFactory)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlReportGenerator"/> class.
        /// </summary>
        /// <param name="inheritanceDiagramRenderer">
        /// The (injected) <see cref="IInheritanceDiagramRenderer"/>; a default instance is used when null.
        /// </param>
        /// <param name="associationDiagramRenderer">
        /// The (injected) <see cref="IAssociationDiagramRenderer"/>; a default instance is used when null.
        /// </param>
        /// <param name="loggerFactory">
        /// The (injected) <see cref="ILoggerFactory"/> used to set up logging
        /// </param>
        public HtmlReportGenerator(IInheritanceDiagramRenderer? inheritanceDiagramRenderer, IAssociationDiagramRenderer? associationDiagramRenderer, ILoggerFactory? loggerFactory = null) : base(loggerFactory)
        {
            this.logger = loggerFactory == null ? NullLogger<HtmlReportGenerator>.Instance : loggerFactory.CreateLogger<HtmlReportGenerator>();

            this.inheritanceDiagramRenderer = inheritanceDiagramRenderer ?? new InheritanceDiagramRenderer(loggerFactory);
            this.associationDiagramRenderer = associationDiagramRenderer ?? new AssociationDiagramRenderer(loggerFactory);
        }

        /// <summary>
        /// Queries the name of the report type that is generated by the current <see cref="IReportGenerator"/>
        /// </summary>
        /// <returns>
        /// human-readable name of the report type
        /// </returns>
        public string QueryReportType()
        {
            return "html";
        }

        /// <summary>
        /// Generates a table that contains all classes, attributes and their documentation
        /// </summary>
        /// <param name="modelPath">
        /// the path to the Ecore model of which the report is to be generated.
        /// </param>
        /// <param name="customHtml">
        /// optional custom HTML that is injected into the report at the custom-HTML injection point.
        /// </param>
        /// <returns>
        /// the content of an HTML report in a string
        /// </returns>
        public string GenerateReport(FileInfo modelPath, string customHtml = "")
        {
            if (modelPath == null)
            {
                throw new ArgumentNullException(nameof(modelPath));
            }

            var sw = Stopwatch.StartNew();

            this.logger.LogInformation("Start Generating Html report tables");

            var template = this.Templates["ecore-to-html-docs"];

            var rootPackage = this.LoadRootPackage(modelPath);

            var payload = CreateHandlebarsPayload(rootPackage);

            var inheritanceDiagramSvg = this.inheritanceDiagramRenderer.SvgRender(payload);

            var classInheritanceDiagrams = new Dictionary<string, string>();
            var classAssociationDiagrams = new Dictionary<string, string>();

            foreach (var eClass in payload.Classes)
            {
                var anchor = eClass.QueryAnchorId();

                // a per-class inheritance tree is only meaningful when the class participates in a hierarchy
                if (eClass.ESuperTypes.Any() || eClass.QuerySpecializations(payload.Classes).Any())
                {
                    classInheritanceDiagrams[anchor] = this.inheritanceDiagramRenderer.SvgRenderForClass(eClass, payload);
                }

                var associationSvg = this.associationDiagramRenderer.SvgRenderForClass(eClass, payload);
                if (!string.IsNullOrEmpty(associationSvg))
                {
                    classAssociationDiagrams[anchor] = associationSvg;
                }
            }

            var generatedHtml = template(new
            {
                Payload = payload,
                InheritanceDiagramSvg = inheritanceDiagramSvg,
                ClassInheritanceDiagrams = classInheritanceDiagrams,
                ClassAssociationDiagrams = classAssociationDiagrams,
                CustomHtml = customHtml
            });

            this.logger.LogInformation("Generated HTML report in {ElapsedTime} [ms]", sw.ElapsedMilliseconds);

            return generatedHtml;
        }

        /// <summary>
        /// Generates a table that contains all classes, attributes and their documentation
        /// </summary>
        /// <param name="modelPath">
        /// the path to the Ecore model of which the report is to be generated.
        /// </param>
        /// <param name="outputPath">
        /// the path, including filename, where the output is to be generated.
        /// </param>
        public void GenerateReport(FileInfo modelPath, FileInfo outputPath)
        {
            this.GenerateReport(modelPath, outputPath, string.Empty);
        }

        /// <summary>
        /// Generates an HTML report and writes it to the provided <paramref name="outputPath"/>.
        /// </summary>
        /// <param name="modelPath">
        /// the path to the Ecore model of which the report is to be generated.
        /// </param>
        /// <param name="outputPath">
        /// the path, including filename, where the output is to be generated.
        /// </param>
        /// <param name="customHtml">
        /// custom HTML that is injected into the report at the custom-HTML injection point; pass
        /// <see cref="string.Empty"/> when none is required.
        /// </param>
        public void GenerateReport(FileInfo modelPath, FileInfo outputPath, string customHtml)
        {
            if (modelPath == null)
            {
                throw new ArgumentNullException(nameof(modelPath));
            }

            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            var sw = Stopwatch.StartNew();

            var generatedHtml = this.GenerateReport(modelPath, customHtml);

            if (outputPath.Exists)
            {
                outputPath.Delete();
            }

            using var writer = outputPath.CreateText();
            writer.Write(generatedHtml);

            this.logger.LogInformation("Generated and saved HTML report in {ElapsedTime} [ms]", sw.ElapsedMilliseconds);
        }

        /// <summary>
        /// Verifies whether the extension of the <paramref name="outputPath"/> is valid or not
        /// </summary>
        /// <param name="outputPath">
        /// The subject <see cref="FileInfo"/> to check
        /// </param>
        /// <returns>
        /// A Tuple of bool and string, where the string contains a description of the verification.
        /// Either stating that the extension is valid or not.
        /// </returns>
        public override Tuple<bool, string> IsValidReportExtension(FileInfo outputPath)
        {
            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            if (outputPath.Extension == ".html")
            {
                return new Tuple<bool, string>(true, ".html is a supported report extension");
            }

            return new Tuple<bool, string>(false,
                $"The Extension of the output file '{outputPath.Extension}' is not supported. Supported extensions is '.html'");
        }

        /// <summary>
        /// Register the code templates
        /// </summary>
        protected override void RegisterTemplates()
        {
            this.RegisterEmbeddedTemplate("ecore-to-html-docs");
        }
    }
}
