// ------------------------------------------------------------------------------------------------
// <copyright file="MarkdownReportGenerator.cs" company="Starion Group S.A.">
//
//   Copyright 2017-2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace ECoreNetto.Reporting.Generators
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;

    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.Abstractions;

    /// <summary>
    /// The purpose of the <see cref="MarkdownReportGenerator"/> is to generate a Markdown report of an
    /// Ecore Model
    /// </summary>
    public class MarkdownReportGenerator : HandleBarsReportGenerator, IMarkdownReportGenerator
    {
        /// <summary>
        /// The <see cref="ILogger"/> used to log
        /// </summary>
        private readonly ILogger<MarkdownReportGenerator> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="MarkdownReportGenerator"/> class.
        /// </summary>
        /// <param name="loggerFactory">
        /// The (injected) <see cref="ILoggerFactory"/> used to set up logging
        /// </param>
        public MarkdownReportGenerator(ILoggerFactory? loggerFactory = null) : base(loggerFactory)
        {
            this.logger = loggerFactory == null ? NullLogger<MarkdownReportGenerator>.Instance : loggerFactory.CreateLogger<MarkdownReportGenerator>();
        }

        /// <summary>
        /// Queries the name of the report type that is generated by the current <see cref="IReportGenerator"/>
        /// </summary>
        /// <returns>
        /// human-readable name of the report type
        /// </returns>
        public string QueryReportType()
        {
            return "markdown";
        }

        /// <summary>
        /// Generates a table that contains all classes, attributes and their documentation
        /// </summary>
        /// <param name="modelPath">
        /// /// the path to the Ecore model of which the report is to be generated.
        /// </param>
        /// <returns>
        /// the content of a Markdown report in a string
        /// </returns>
        public string GenerateReport(FileInfo modelPath)
        {
            if (modelPath == null)
            {
                throw new ArgumentNullException(nameof(modelPath));
            }

            return this.GenerateReport(new[] { this.LoadRootPackage(modelPath) });
        }

        /// <summary>
        /// Generates a single combined Markdown report of the entry model together with every cross-referenced
        /// model that is reachable from it.
        /// </summary>
        /// <param name="modelPath">
        /// the path to the entry Ecore model of which the combined report is to be generated.
        /// </param>
        /// <returns>
        /// the content of a Markdown report in a string
        /// </returns>
        public string GenerateCombinedReport(FileInfo modelPath)
        {
            if (modelPath == null)
            {
                throw new ArgumentNullException(nameof(modelPath));
            }

            return this.GenerateReport(this.LoadRootPackages(modelPath));
        }

        /// <summary>
        /// Generates a single combined Markdown report of every <c>.ecore</c> model in the provided directory.
        /// </summary>
        /// <param name="inputDirectory">
        /// the directory that contains the <c>.ecore</c> models of which the combined report is to be generated.
        /// </param>
        /// <returns>
        /// the content of a Markdown report in a string
        /// </returns>
        public string GenerateCombinedReport(DirectoryInfo inputDirectory)
        {
            if (inputDirectory == null)
            {
                throw new ArgumentNullException(nameof(inputDirectory));
            }

            return this.GenerateReport(this.LoadRootPackages(inputDirectory));
        }

        /// <summary>
        /// Generates the Markdown report for the provided root <see cref="EPackage"/>s.
        /// </summary>
        /// <param name="rootPackages">
        /// the root <see cref="EPackage"/>s whose classifiers are documented in the report.
        /// </param>
        /// <returns>
        /// the content of a Markdown report in a string
        /// </returns>
        private string GenerateReport(IReadOnlyList<EPackage> rootPackages)
        {
            var sw = Stopwatch.StartNew();

            this.logger.LogInformation("Start Generating Markdown report");

            var template = this.Templates["ecore-to-markdown-docs"];

            var payload = CreateHandlebarsPayload(rootPackages);

            var generatedMarkdown = template(payload);

            this.logger.LogInformation("Generated Markdown report in {ElapsedTime} [ms]", sw.ElapsedMilliseconds);

            return generatedMarkdown;
        }

        /// <summary>
        /// Generates a Markdown document with a table that contains all classes, attributes and their documentation
        /// </summary>
        /// <param name="modelPath">
        /// the path to the Ecore model of which the report is to be generated.
        /// </param>
        /// <param name="outputPath">
        /// the path, including filename, where the output is to be generated.
        /// </param>
        public void GenerateReport(FileInfo modelPath, FileInfo outputPath)
        {
            if (modelPath == null)
            {
                throw new ArgumentNullException(nameof(modelPath));
            }

            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            this.WriteToFile(this.GenerateReport(modelPath), outputPath);
        }

        /// <summary>
        /// Generates a single combined Markdown report of the entry model together with every cross-referenced
        /// model that is reachable from it, and writes it to the provided <paramref name="outputPath"/>.
        /// </summary>
        /// <param name="modelPath">
        /// the path to the entry Ecore model of which the combined report is to be generated.
        /// </param>
        /// <param name="outputPath">
        /// the path, including filename, where the output is to be generated.
        /// </param>
        public void GenerateCombinedReport(FileInfo modelPath, FileInfo outputPath)
        {
            if (modelPath == null)
            {
                throw new ArgumentNullException(nameof(modelPath));
            }

            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            this.WriteToFile(this.GenerateCombinedReport(modelPath), outputPath);
        }

        /// <summary>
        /// Generates a single combined Markdown report of every <c>.ecore</c> model in the provided directory
        /// and writes it to the provided <paramref name="outputPath"/>.
        /// </summary>
        /// <param name="inputDirectory">
        /// the directory that contains the <c>.ecore</c> models of which the combined report is to be generated.
        /// </param>
        /// <param name="outputPath">
        /// the path, including filename, where the output is to be generated.
        /// </param>
        public void GenerateCombinedReport(DirectoryInfo inputDirectory, FileInfo outputPath)
        {
            if (inputDirectory == null)
            {
                throw new ArgumentNullException(nameof(inputDirectory));
            }

            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            this.WriteToFile(this.GenerateCombinedReport(inputDirectory), outputPath);
        }

        /// <summary>
        /// Writes the generated Markdown to the provided <paramref name="outputPath"/>, overwriting an existing file.
        /// </summary>
        /// <param name="generatedMarkdown">
        /// the generated Markdown content.
        /// </param>
        /// <param name="outputPath">
        /// the path, including filename, where the output is to be written.
        /// </param>
        private void WriteToFile(string generatedMarkdown, FileInfo outputPath)
        {
            var sw = Stopwatch.StartNew();

            if (outputPath.Exists)
            {
                outputPath.Delete();
            }

            using var writer = outputPath.CreateText();
            writer.Write(generatedMarkdown);

            this.logger.LogInformation("Generated Markdown report in {ElapsedTime} [ms]", sw.ElapsedMilliseconds);
        }

        /// <summary>
        /// Verifies whether the extension of the <paramref name="outputPath"/> is valid or not
        /// </summary>
        /// <param name="outputPath">
        /// The subject <see cref="FileInfo"/> to check
        /// </param>
        /// <returns>
        /// A Tuple of bool and string, where the string contains a description of the verification.
        /// Either stating that the extension is valid or not.
        /// </returns>
        public override Tuple<bool, string> IsValidReportExtension(FileInfo outputPath)
        {
            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            if (outputPath.Extension == ".md")
            {
                return new Tuple<bool, string>(true, ".md is a supported report extension");
            }

            return new Tuple<bool, string>(false,
                $"The Extension of the output file '{outputPath.Extension}' is not supported. Supported extensions is '.md'");
        }

        /// <summary>
        /// Register the code templates
        /// </summary>
        protected override void RegisterTemplates()
        {
            this.RegisterEmbeddedTemplate("ecore-to-markdown-docs");
        }
    }
}
