<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <Title>ECoreNetto.HandleBars</Title>
        <Version>7.0.9</Version>
        <Description>HandleBarHelpers for use in combination with the ECoreNetto library to support HandleBarHelpers based code generation</Description>
        <PackageId>ECoreNetto.HandleBars</PackageId>
        <AssemblyTitle>EcoreNetto.HandleBars</AssemblyTitle>
        <PackageTags>Ecore HandleBars modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Update] ECoreNetto.Extensions to version 7.0.9
            [Update] Microsoft.SourceLink.GitHub to version 10.0.103
            [Update] Handlebars.Net.Helpers to version 2.5.5
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Handlebars.Net.Helpers" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ECoreNetto.Extensions\ECoreNetto.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>

</Project>
