<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <Title>ECoreNetto.Extensions</Title>
        <Version>7.0.9</Version>
        <Description>Extension methods for the ECoreNetto library that are typically used to support code generation</Description>
        <PackageId>ECoreNetto.Extensions</PackageId>
        <AssemblyTitle>EcoreNetto.Extensions</AssemblyTitle>
        <PackageTags>Ecore modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Update] to ECoreNetto version 7.0.9
            [Update] Microsoft.SourceLink.GitHub to version 10.0.203
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ECoreNetto\ECoreNetto.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>
</Project>
