<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <Title>ECoreNetto.Reporting</Title>
        <Version>7.0.9</Version>
        <Description>Ecore Reporting use in combination with the ECoreNetto library generate reports</Description>
        <PackageId>ECoreNetto.Reporting</PackageId>
        <AssemblyTitle>EcoreNetto.Reporting</AssemblyTitle>
        <PackageTags>Ecore HandleBars Reporting modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Update] ECoreNetto.HandleBars version 7.0.9
            [Update] System.IO.Packaging version 10.0.7
            [Update] Microsoft.SourceLink.GitHub to version 10.0.203
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Templates\ecore-to-html-docs.hbs" />
      <None Remove="Templates\ecore-to-markdown-docs.hbs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Templates\ecore-to-html-docs.hbs">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="Templates\ecore-to-markdown-docs.hbs">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ECoreNetto.HandleBars\ECoreNetto.HandleBars.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" />
    </ItemGroup>

    <ItemGroup Label="Transitive Dependency overrides">
        <PackageReference Include="System.IO.Packaging" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>

</Project>
