<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="Package">
        <LangVersion>14.0</LangVersion>
        <Title>ECoreNetto.Tools</Title>
        <Description>A command line application that processes an Ecore file and generates various reports.</Description>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <PackAsTool>true</PackAsTool>
        <PackageId>ECoreNetto.Tools</PackageId>
        <ToolCommandName>ecoretools</ToolCommandName>
        <Version>8.0.1</Version>
        <ImplicitUsings>disable</ImplicitUsings>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <PackageTags>Ecore HandleBars Reporting modeltopia</PackageTags>
        <PackageReleaseNotes>
            [Update] ECoreNetto.Reporting to version 7.0.9
            [Update] Autofac.Extensions.DependencyInjection to version 11.0.0
            [Update] Microsoft.Extensions.Http to vesion 10.0.7
            [Update] Microsoft.Extensions.Hosting to vesion 10.0.7
            [Update] System.CommandLine to version 2.0.7
            [Update] Spectre.Console to version 0.54.0
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\ascii-art.txt" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\ascii-art.txt">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="System.CommandLine" />
        <PackageReference Include="Spectre.Console" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="icon.ico" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ECoreNetto.Reporting\ECoreNetto.Reporting.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>

</Project>
