<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>ECoreNetto.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit.Console" />
        <PackageReference Include="NUnit3TestAdapter">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ECoreNetto\ECoreNetto.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\TestData\ecore.ecore" Link="Data\ecore.ecore">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\TestData\recipe.ecore" Link="Data\recipe.ecore">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\TestData\wizardEcore.ecore" Link="Data\wizardEcore.ecore">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="..\TestData\capella\*.ecore" Link="Data\capella\%(Filename)%(Extension)">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>